#!/bin/bash
msg=$(head -n 1 "$1")
is_merge_commit=$(git rev-parse -q --verify MERGE_HEAD)
if [ -z "$is_merge_commit" ]; then
    msg_length=${#msg}
    max_length=72
    if ((msg_length > max_length)); then
        echo "[ERROR!] commit-msg: Commit message cannot exceed $max_length."
        exit 1
    fi
fi
