#!/bin/bash

exec < /dev/tty
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"
if [[ "$(docker images -q "test" 2> /dev/null)" == "" ]];then
  read -p "[pre-commit hook] Test images does not exist... do you wish to build this image? (y/n) " yn
  case $yn in 
    [Yy] ) docker compose --profile=test build;;
    * ) exit 1;;
  esac
fi

docker compose run -T --rm test
exit_status=$?
docker compose --profile=test down --volumes
if [ "$exit_status" -ne 0 ]; then
  echo "Make test or check did not pass please resolve issues and try again."
  exit 1
fi

if [ -z "$(which sblint)" ]; then
    echo "WARNING! sblint not found. Given up to run it."
    exit 0
fi

error_count=$(sblint | wc -l | tr -d '[[:space:]]')

if [ "$error_count" -gt "0" ]; then
    echo "Failed to commit because $error_count errors are found by SBLint."
    exit 1
fi
