version: "3.4"

x-test-info: &test_info
  command: --test
  depends_on:
    - test-db
  environment:
    POSTGRES_PORT: 5432
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
    POSTGRES_DBNAME: postgres
    POSTGRES_HOST: test-db

services:
  test-db:
    image: postgres:alpine3.18
    container_name: test-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  test-sample:
    image: sample-target
    <<: *test_info
