version: "3"

x-healthcheck: &healthcheck
  test:
    - "CMD"
    - sh
    - -c
    - misc/pulse
  interval: 30s
  timeout: 20s
  retries: 1

x-module-info: &module_info
  image: ${MODULE_NAME:-module}-${TARGET:-target}
  container_name: ${MODULE_NAME:-module}-${TARGET:-target}

x-build: &build
  context: ./modules/${MODULE_NAME:-module}
  dockerfile: ${DOCKERFILE:-../../misc/modules/Dockerfile}
  target: ${TARGET:-base}
  args:
    - ADDITIONAL_APK=${ADDITIONAL_APK:-}
    - MODULE_NAME=${MODULE_NAME:-module}

x-module-environment: &module_environment
  POSTGRES_DBNAME: ${POSTGRES_DBNAME:-db_name}
  POSTGRES_PORT: ${POSTGRES_PORT:-5432}
  POSTGRES_USER: ${POSTGRES_USER:-user}
  PERSISTENCE_MODULE: eventsourcing.postgres

x-cloak-env: &cloak-env
  env_file: ./modules/keycloak/.env

x-cloak-extends: &cloak-extends
  file: ./modules/keycloak/cloak.yml


services:
  module:
    profiles: ["module_builder"]
    <<: *module_info
    build:
      <<: *build

  sample:
    image: sample-target
    container_name: sample
    command: -h
    healthcheck:
      <<: *healthcheck
    environment:
      <<: *module_environment
      POSTGRES_PASSWORD: ${POSTGRES_SAMPLE_PASSWORD:-sample}
      POSTGRES_HOST: sample-db
      MODULE_DIR: sample
    depends_on:
      - sample-db
    #volumes:
      #- ./modules/sample:/sample

  sample-db:
    image: postgres:alpine3.18
    container_name: sample-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-sample}
      POSTGRES_PASSWORD: ${POSTGRES_USER_PASSWORD:-sample}

  cloak:
    <<: *cloak-env
    extends:
      <<: *cloak-extends
      service: keycloak
    depends_on:
      - cloak-db

  cloak-db:
    <<: *cloak-env
    extends:
      <<: *cloak-extends
      service: db
    volumes:
      - cloak-data:/var/lib/postgresql/data

  web:
    extends:
      file: ./modules/nginx/nginx.yml
      service: web

  ui:
    extends:
      file: ./modules/frontend/ui.yml
      service: ui
    container_name: ui
    command: dev


volumes:
  cloak-data:
